use "stdlib"

fn graphite() {
    var i = 0

    std.println("")
    std.println("    ╔══════════════════════════╗")
    std.println("    ║        <GRAPHITE>        ║")
    std.println("    ╠══════════════════════════╣")

    while (i < 3) {
        if (i == 0) {
            std.println("    ║   -Simple syntax         ║");
        } else {
            if (i == 1) {
                std.println("    ║   -User control          ║")
            } else {
                std.println("    ║   -Built from scratch    ║")
            }
        }

        i = i + 1
    }

    std.println("    ╚══════════════════════════╝")
    std.println("")
    std.println("    Simple by design.")
    std.println("    Powerful by choice.")
}

graphite()